apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arc-runner-rolebinding
  namespace: meme-bot
subjects:
- kind: ServiceAccount
  name: arc-runner-set-gha-rs-kube-mode
  namespace: arc-runners
roleRef:
  kind: Role
  name: arc-runner-role
  apiGroup: rbac.authorization.k8s.io
