apiVersion: v1
kind: Secret
metadata:
  name: meme-bot-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  TELEGRAM_BOT_TOKEN: {{ .Values.secrets.telegramBotToken | b64enc | quote }}
  YANDEX_OAUTH_TOKEN: {{ .Values.secrets.yandexOAuthToken | b64enc | quote }}
  YANDEX_ART_FOLDER_ID: {{ .Values.secrets.yandexArtFolderId | b64enc | quote }}
  FUSION_BRAIN_API_KEY: {{ .Values.secrets.fusionBrainApiKey | b64enc | quote }}
  FUSION_BRAIN_SECRET_KEY: {{ .Values.secrets.fusionBrainSecretKey | b64enc | quote }}
  MEME_DEBUG: {{ .Values.secrets.memeDebug | b64enc | quote }}
