name: Build, Push, and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_IMAGE: azalio/meme-bot
  KUBE_NAMESPACE: meme-bot
  HELM_CHART_PATH: ./charts
#   KANIKO_CACHE_ARGS: "--cache=true --cache-copy-layers=true --cache-ttl=24h"

jobs:
    docker:
        runs-on: arc-runner-set
        steps:
          - uses: actions/checkout@master
          - name: Kaniko build
            uses: aevea/action-kaniko@master
            with:
              image: aevea/kaniko
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}
              cache: true
              cache_registry: aevea/cache

#   deploy:
#     runs-on: arc-runner-set
#     needs: build-and-push

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Helm
#       uses: azure/setup-helm@v3
#       with:
#         version: 'v3.8.0'

#     - name: Configure Kubernetes
#       uses: azure/setup-kubectl@v3
#       with:
#         version: 'v1.30.0'

#     - name: Deploy to Kubernetes
#       run: |
#         helm upgrade --install meme-bot ${{ env.HELM_CHART_PATH }} \
#           --namespace ${{ env.KUBE_NAMESPACE }} \
#           --set image.repository=${{ env.DOCKER_IMAGE }} \
#           --set image.tag=${{ github.sha }}
