name: Build, Push, and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_IMAGE: azalio/meme-bot
  KUBE_NAMESPACE: meme-bot
  HELM_CHART_PATH: ./charts

jobs:
  build-and-push:
    runs-on: arc-runner-set
    container:
      image: gcr.io/kaniko-project/executor:debug
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and push with Kaniko
      run: |
        /kaniko/executor \
          --dockerfile=Dockerfile \
          --context=. \
          --destination=${{ env.DOCKER_IMAGE }}:${{ github.sha }} \
          --cache=true \
          --cache-repo=${{ env.DOCKER_IMAGE }}/cache \
          --verbosity=info

  deploy:
    runs-on: arc-runner-set
    needs: build-and-push

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.8.0'

    - name: Configure Kubernetes
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.30.0'

    - name: Deploy to Kubernetes
      run: |
        helm upgrade --install meme-bot ${{ env.HELM_CHART_PATH }} \
          --namespace ${{ env.KUBE_NAMESPACE }} \
          --set image.repository=${{ env.DOCKER_IMAGE }} \
          --set image.tag=${{ github.sha }}
